### ISSUE TITLE
Capture all host logs for auditing purposes

### ISSUE THREAD

**Issue by sharms** [18F/cg-atlas#156] opened 2016-09-07 17:59 UTC
In order have all platform logs available for auditing as Cloud Operations I want to send bosh job logs to CloudWatch.

**Acceptance Criteria**
- [x] /var/vcap/\* is sent to CloudTrail via AWS Logs

**Implementation Sketch**
- Add a [pre-start job configuration](https://bosh.io/docs/pre-start.html) to our [awslogs release](https://github.com/18F/cg-awslogs-boshrelease) that 
  - iterates over something like `/var/vcap/sys/logs/*/*`
  -  and generates an [agent config file](http://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AgentReference.html) to send all discovered logs to cloudwatch

**Comment by cnelson** [comment] 2016-10-21 13:53
Seems like this story needs an implementation sketch before we could think about moving forward on it. So... how do we propose to actually do this? I see a few possibilities:

### Maintain an exhaustive list of logs to capture in the release

This seems to be [what we are doing today](https://github.com/18F/cg-awslogs-boshrelease/blob/master/jobs/awslogs/templates/config/awslogs.conf.erb). We'd just need to list everything else here and commit to keeping it up-to-date.

### Modify our other releases to declare which logs they generate should be archived

See [Compartmentalizing CloudWatch Logs Agent Configuration Files](http://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AgentReference.html) for an idea of how we could do this.  We could have each release / job write a configuration file out declaring which of it's logs should be backed up.

### Modify the awslog startup scripts to generate a configuration on boot

I'm envisioning we'd have a small script that would iterate over something like `/var/vcap/sys/logs/*/*.log` and append each file to the awslogs configuration before start.

Thoughts? Better Ideas?

**Comment by datn** [comment] 2016-10-31 23:37
Testing more comprehensive log capture on a test host.

**Comment by datn** [comment] 2016-10-31 23:48
Committing my initial attempt at the pre-start script: https://github.com/18F/cg-awslogs-boshrelease/pull/5

Needs more work tomorrow, tho --

**Comment by datn** [comment] 2016-11-01 23:09
The above PR seems ready to me. If @cnelson approves and merges, I can test and then push this to the next column.

**Comment by datn** [comment] 2016-11-02 18:50
Changes merged to master -- now verifying we are seeing new log events in AWS console.

**Comment by datn** [comment] 2016-11-02 18:51
Deployed awslogs changes to logsearch --

**Comment by datn** [comment] 2016-11-02 19:12
Didn't work because the additional config dir was being improperly specified.

**Comment by datn** [comment] 2016-11-02 22:56
Okay, in testing it looks as if {instance_id} is not unique enough and is causing zillions of this error:

```
cwlogs.push.publisher - WARNING - 12345 - Thread-67 - Multiple agents might be sending log events to log stream (nats_to_syslog i-a89101112) with sequence token (LONG_STRING_OF_DIGITS|none). This could cause duplicates and is not recommended.
```

I might need to amend the log stream identifier, or there might be another problem.

**Comment by datn** [comment] 2016-11-03 17:44
Okay, after testing different log_stream_name configs (didn't have much hope for that), I conclude that the aggressive harvesting of all files under `/var/vcap/sys/log` is causing sequence token errors. I'm going to be smarter about which files to ingest in the pre-start script, because gathering all valid logs for compliance is the most important goal here.

**Comment by datn** [comment] 2016-11-03 19:21
Okay, I have a unique log stream name & a sane group name and am excluding very obviously non-ingestable logs from the config (files that are not text or empty, and files that have a rotation timestamp) to avoid uselessly spawning log readers. No sequence errors nor multiple-agent errors any more.

**Comment by datn** [comment] 2016-11-03 23:44
Just waiting on a thumbs-up and merge so we can redeploy and test.

**Comment by datn** [comment] 2016-11-04 16:58
Waiting on merge -- https://github.com/18F/cg-awslogs-boshrelease/pull/7

**Comment by datn** [comment] 2016-11-07 18:32
I'm seeing logs with the new log stream name pattern everywhere I look in CloudWatch. I'm just not sure if there's any deploy I need to manually kick off to be sure we're collecting everything everywhere, but this looks good to me.

**Comment by mogul** [comment] 2016-11-09 17:49
@sharms will accept later today

**Comment by sharms** [comment] 2016-11-09 22:42
The current implementation triggers on `pre-start` which means that it will be executed before any jobs start.  The current code will not add any logs during this time, as it searches for log files which have been written to (1), which do not exist on a stemcell upgrade.

This worked on staging as these systems are frequently rebooted without cause, however it is rare we reboot production.  

**Recommendations:**
1. Move log detection into startup script

**References:**
1. https://github.com/18F/cg-awslogs-boshrelease/blob/master/jobs/awslogs/templates/bin/pre-start#L9

**Comment by cnelson** [comment] 2016-11-09 23:06
Good catch!  My bad for suggesting pre-start.

**Comment by cnelson** [comment] 2016-11-25 15:31
@datn Did you address Steve's feedback about this running in pre-start?

I'm not sure what the best approach is here, but I can see  a few options:
- Toss a fairly long sleep() into the start of this job to give everything else a chance to start before we scan for logs
- Move this code to a post-start job and extend it to also restart/HUP the agent?
- Inject a cron job to scan for new logs and restart the agent any time it finds them so we continually add new logs as they are created

**Comment by jmcarp** [comment] 2016-11-25 15:34
Post-deploy might be a better place to move this, since we'd want all jobs to have started before we set up awslogs: https://bosh.io/docs/post-deploy.html. Or a cron job.

**Comment by datn** [comment] 2016-11-25 18:08
I missed the notification that this went back into ready, will look at it and everyone's helpful suggestions today.

**Comment by datn** [comment] 2016-11-25 19:02
I'm not understanding the problem @sharms points out, so I'll ask for clarification in channel.

**Comment by datn** [comment] 2016-11-25 20:44
https://github.com/18F/cg-awslogs-boshrelease/pull/11

**Comment by cnelson** [comment] 2016-11-28 17:24
Tested on admin-ui in staging, and while new logs are being added to the awslogs config file, they do not appear to be making it to cloudwatch.

I think the problem is that monit is not in the root user's path by default, so [this call to restart](https://github.com/18F/cg-awslogs-boshrelease/blob/master/jobs/awslogs/templates/bin/additional-logs.sh#L20) isn't executing.

**Comment by cnelson** [comment] 2016-12-05 15:32
https://github.com/18F/cg-awslogs-boshrelease/pull/12 uses a new approach to ensure logs are captured even on short-lived / ephemeral VMs

**Comment by mogul** [comment] 2016-12-12 17:49
@datn can you accept this one?

**Comment by rogeruiz** [comment] 2016-12-14 17:51
Accepting this one.

**Closed as completed by rogeruiz** 2016-12-14 17:51 UTC
Labels: Atlas, HighBar
